##############
### local
##############
server:
  port: 8080
spring:
  h2:
    # h2 DB
    console:
      enabled: true
      path: /h2-console
  # Database Platform
  sql:
    init:
      platform: h2
      mode: embedded


# spring boot - actuator expose
management:
  endpoints:
    health:
      show-details: always
      enabled: true
    loggers:
      enabled: true  
    prometheus:
      enabled: true
    gateway:
      enabled: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
  cloud:
    gateway:
      routes:
        - id: nginx-service
          uri: http://localhost:8080
          predicates:
            - Path=/nginx/**
          filters:
            - RewritePath=/(?<path>.*),/$\{path}
        - id: httpd-service
          uri: http://localhost:8081
          predicates:
            - Path=/apache/**
          filters:
            - RewritePath=/(?<path>.*),/$\{path}
# app
app-info:
  node-ip: "192.168.0.1"
  pod-ip: "192.168.0.1"
  pod-name: "test"
  app-name: "edu11"

springdoc:
  show-actuator: true  # actuator swagger 노출
  swagger-ui:
    groups-order: DESC
    #operations-sorter: alpha
    #tags-sorter: alpha
    disable-swagger-default-url: true
    #doc-expansion: none

logging:
  level:
    com.kt.edu: debug
    org.springframework.cloud.gateway: debug

